### ISSUE TITLE
--switch gets autocorrected to — on OSX

### ISSUE THREAD

**Issue by matijaabicic** [matijaabicic/urban-slack#24]
Although this is a OS X setting that can be changed...I don't think anyone will actually bother to change it. I want to come up with a more user-friendly solution to this

**Comment by Si1kIfY** [comment]
Yep just had this present

```
/urban —public FOMO
```

> No definition.

I'll have a look into it later

**Comment by matijaabicic** [comment]
If I add "—" as a switch indicator
